### ISSUE TITLE
Code execution stops when calling DLL methods using Koffi

### ISSUE THREAD

**Issue by IgorSamer** [Koromix/rygel#4]

**Comment by Koromix** [comment]
Thanks! Looking into it during the week-end :)

I'm merging my two monorepos into one, that's why the issue has been transferred ;)

**Comment by IgorSamer** [comment]
> Thanks! Looking into it during the week-end :)
> 
> I'm merging my two monorepos into one, that's why the issue has been transferred ;)

Got it!

And just to let you know and clear all doubts, I tested the following example with node-ffi-napi and just added node-segfault-handler to see if anything happened. And the truth is that the same error occurs when using node-ffi-napi, but the execution is not terminated (if it is in a loop, for example) and Node returns the expected value.

```
const SegfaultHandler = require('segfault-handler');

SegfaultHandler.registerHandler('crash.log');

const ffi = require('ffi-napi');

const EasyInner = new ffi.Library('EasyInner', {
    'FecharPortaComunicacao': ['void', []],
    'DefinirTipoConexao': ['char', ['int']],
    'AbrirPortaComunicacao': ['char', ['int']]
});

EasyInner.FecharPortaComunicacao();

if (EasyInner.DefinirTipoConexao(2) == 0) {
    console.log('Setted!');

    const open = EasyInner.AbrirPortaComunicacao(3570);

    if (open == 0) {
        console.log('Opened!');
    } else {
        console.log(`Error on open! (${open})`);
    }
} else {
    console.log('Error on set!');
}
```

And the result is:

```
PS C:\Users\igore\OneDrive\Área de Trabalho\Desenvolvimento\NAPI> node index
ERROR 1 (below)
Setted!
ERROR 2 (below)
Error on open! (8)
ERROR 3 (below)
PS C:\Users\igore\OneDrive\Área de Trabalho\Desenvolvimento\NAPI>
```

ERROR 1:

> PID 284 received SIGSEGV for address: 0x7614df72
> SymInit: Symbol-SearchPath: '.;C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'igore'
> OS-Version: 10.0.19045 () 0x300-0x1
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\StackWalker.cpp (922): StackWalker::ShowCallstack
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
> 778ACEE8 (ntdll): (filename not available): LdrSetDllManifestProber
> 778A916B (ntdll): (filename not available): RtlUnwind
> 778B5006 (ntdll): (filename not available): KiUserExceptionDispatcher
> 1005CA99 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10040206 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1003FB71 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10024F45 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10005CE5 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10005AB8 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10004B1B (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10006260 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 100268E7 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 74EAAD68 (ffi_bindings): (filename not available): ffi_call_i386
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\ffi-napi\deps\libffi\src\x86\ffi.c (392): ffi_call_int
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\ffi-napi\src\ffi.cc (255): FFI::FFI::FFICall
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\node-addon-api\napi-inl.h (74): Napi::details::WrapCallback<<lambda_1ff54cb808b40ce624d944888a4559a9> >
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\node-addon-api\napi-inl.h (125): Napi::details::CallbackData<void (__cdecl*)(Napi::CallbackInfo const &),void>::Wrapper
> 00F58F7B (node): (filename not available): cppgc::internal::LargePage::PayloadStart
> 017974EB (node): (filename not available): v8::internal::Builtins::code
> 017976DF (node): (filename not available): v8::internal::Builtins::code
> 017975A6 (node): (filename not available): v8::internal::Builtins::code
> 0185826B (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap

ERROR 2:

> PID 284 received SIGSEGV for address: 0x7614df72
> SymInit: Symbol-SearchPath: '.;C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'igore'
> OS-Version: 10.0.19045 () 0x300-0x1
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\StackWalker.cpp (922): StackWalker::ShowCallstack
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
> 778ACEE8 (ntdll): (filename not available): LdrSetDllManifestProber
> 778A916B (ntdll): (filename not available): RtlUnwind
> 778B5006 (ntdll): (filename not available): KiUserExceptionDispatcher
> 1005CA99 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10040206 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1003FB71 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1002502C (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10004FA6 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10006334 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10026937 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 74EAAD68 (ffi_bindings): (filename not available): ffi_call_i386
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\ffi-napi\deps\libffi\src\x86\ffi.c (392): ffi_call_int
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\ffi-napi\src\ffi.cc (255): FFI::FFI::FFICall
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\node-addon-api\napi-inl.h (74): Napi::details::WrapCallback<<lambda_1ff54cb808b40ce624d944888a4559a9> >
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\node-addon-api\napi-inl.h (125): Napi::details::CallbackData<void (__cdecl*)(Napi::CallbackInfo const &),void>::Wrapper
> 00F58F7B (node): (filename not available): cppgc::internal::LargePage::PayloadStart
> 017974EB (node): (filename not available): v8::internal::Builtins::code
> 017976DF (node): (filename not available): v8::internal::Builtins::code
> 017975A6 (node): (filename not available): v8::internal::Builtins::code
> 0185826B (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap

ERROR 3:

> PID 284 received SIGSEGV for address: 0x7614df72
> SymInit: Symbol-SearchPath: '.;C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'igore'
> OS-Version: 10.0.19045 () 0x300-0x1
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\StackWalker.cpp (922): StackWalker::ShowCallstack
> C:\Users\igore\OneDrive\�rea de Trabalho\Desenvolvimento\NAPI\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
> 778ACEE8 (ntdll): (filename not available): LdrSetDllManifestProber
> 778A916B (ntdll): (filename not available): RtlUnwind
> 778B5006 (ntdll): (filename not available): KiUserExceptionDispatcher
> 1005CA99 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10040206 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1003FB71 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10024F45 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10005CE5 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10005AB8 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 10004A75 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 100061C5 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 100060BF (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1003F805 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1003F70A (EasyInner): (filename not available): RespostaListarUsuariosBio
> 1005EC10 (EasyInner): (filename not available): RespostaListarUsuariosBio
> 778B2AB6 (ntdll): (filename not available): RtlIpv6AddressToStringA
> 7788DE02 (ntdll): (filename not available): RtlActivateActivationContextUnsafeFast
> 7789D912 (ntdll): (filename not available): LdrShutdownProcess
> 7789D795 (ntdll): (filename not available): RtlExitUserProcess
> 772D4113 (KERNEL32): (filename not available): ExitProcess
> 01CD6116 (node): (filename not available): v8::internal::compiler::ToString
> 01CD60D4 (node): (filename not available): v8::internal::compiler::ToString
> 01CD61E4 (node): (filename not available): v8::internal::compiler::ToString
> 01CC760D (node): (filename not available): v8::internal::compiler::ToString
> 772CFA29 (KERNEL32): (filename not available): BaseThreadInitThunk
> 778A7BBE (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
> 778A7B8E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

Knowing this, the only difference is that Koffi terminates execution when detecting these errors while node-ffi-napi does not. That way, when using Koffi in my project with Electron the program would close whenever this failure occurred.

Anyway, I'll be spending the entire weekend at one of my client's establishments just to do these tests directly at the physical turnstile. This way it will be easier to test the real behavior of the equipment and the code to be able to give you more assertive information :)

**Comment by Koromix** [comment]
I've made progress on this issue :)

So far, I think the problem comes from Structured Exception Handling (SEH) being broken inside the DLL because Koffi uses a separate stack (unlike libffi/node-ffi which reuse the caller stack). The Koffi approach has some advantages but it may cause the NT/SEH unwind code to abort because the stack is outside of the native stack.

This is my theory anyway. The EasyInner DLL uses SEH to catch _com_error exception, which happens when .NET 3.5 is not installed, and then return 8. But because SEH may not work when Koffi is involved, the exception seems to go through and then another fatal error happens (segmentation fault) and everything crashes.

This means outside of the .NET error, I don't think anything inside EasyInner will fail with Koffi. I will fix this issue but it is pretty involved, and I'd like to keep the separate stack because it brings us good things.

There may be a way to get the both of both worlds, I'll make some tests next week and keep you informed ;)

**Comment by IgorSamer** [comment]
Allright! Good to hear that! :)

I've made some tests along this morning with my client's turnstile and they were promising. To be honest, I had some crashes again and right now I don't know if the problem involves EasyInner or if it is related to Electron (or both), since after connecting I need to keep a loop to interact with the turnstile through a state machine (as in `SDK EasyInner/Manuais/Manual de Desenvolvimento - EasyInner.pdf` - page 9) and for that reason I don't know if there may be a memory leak - I will do new tests again first directly with Node and later using Electron.

Anyway, tomorrow I will contact the manufacturer again to rent a physical equipment so that I can test more freely on my main computer for development (with the .NET issue already resolved) and thus have more concrete data to be able to tell you about the behavior of libraries.

And since I talked about memory leak, I accept opinions about good practices regarding state machine loops and DLL calls (if I keep the `setInterval` or if I should use another approach, for example) 🤓 

Thanks again for all the effort and attention and as soon as I have the physical turnstile already configured on my computer I will do new tests and let you know!

**Comment by Koromix** [comment]
Thanks for the repro, I will try this weekend :)

**Comment by IgorSamer** [comment]
Any updates mate? 🙏🏻

**Comment by Koromix** [comment]
Sorry, just a lot to do at work ><
I really want to work on this this week-end ++

**Comment by nwrkbiz** [comment]
@IgorSamer just for completeness, are you sure 'stdcall' is the right calli´ng convention?

**Comment by Koromix** [comment]
Good news :)

In the `fiber` git branch I've tried to use Win32 fibers to make sure the thread stack are set right when Koffi executes native code.

It seems to work, because with this change I get the "Error on open!" when .NET 3.5 is not installed (instead of a crash with latest Koffi release).

This branch has other problems right now (callbacks fail) but my hypothesis was correct and looks like I'm on the right track :)

**Comment by Koromix** [comment]
On the other hand I can confirm that this change is quite impactful for performance (33% slower at least).

So I think it will only get used when an explicit "__seh" flag is set in the function definition, or something like that.

**Comment by Koromix** [comment]
Okay, I've found a much better and easier way than using fibers... directly changing the TIB stack limits. Previous testing had left me thinking it was not possible/protected, but I guess I had messed up. This time it worked, which means no slowdown and no need for a special flag!

I've pushed **Koffi 2.2.3-beta.1** to NPM, install with `npm install koffi@beta`.

Hopefully this solves your problems :) Fingers crossed!

**Comment by Koromix** [comment]
Pushed **Koffi 2.2.3-beta.2** that should work better ++ ;)

**Comment by IgorSamer** [comment]
Good news!

The tests this time went as expected on my computer and the test program made in Electron works normally without crashing at any time!

I'm excited to be able to test this weekend with the physical turnstile connected and I'll let you know the results here as soon as I can :)

**Comment by Koromix** [comment]
I've release Koffi 2.2.3 anyway!

Even if in the end it does not solve your issue completely, it's still a good fix :) We can always make a new release if something else happens.

**Comment by IgorSamer** [comment]
Sorry, I couldn't test it over the weekend because I had some unforeseen issues with my project and I had to fix them during those days. I had to reschedule the tests with the physical turnstile for this Thursday 🙌

**Comment by Koromix** [comment]
No problem, I'll wait!

I'll probably release 2.2.6 with new features for #18, just wanted to see if there's anything remaining to do for this issue too ;)

**Comment by IgorSamer** [comment]
Bringing you some news!

I finally managed to do the tests on the physical turnstile and had very promising results!

I was able to generate my app installer normally using `electron-builder` and after installing it on a Windows 11 computer everything worked great and this time with no random crashes!

Communication flows normally through all methods and a single detail is that when I call the `FecharPortaComunicacao` method to end communication with the turnstile the app stops working and then it ends up crashing. When calling this method before the first connection it works normally. The problem is after the connection is established, which makes me imagine that it has something to do with the fact that `setInterval` has accumulated some method calls that could not be executed before the `FecharPortaComunicacao` call.

I used the [segfault-handler](https://www.npmjs.com/package/segfault-handler) to generate the error log when calling the method and here it is:

```
PID 8780 received SIGSEGV for address: 0x76d80a82
SymInit: Symbol-SearchPath: '.;C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest;C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\electron\dist;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Igor'
OS-Version: 10.0.22000 () 0x300-0x1
PID 8780 received SIGSEGV for address: 0x76d80a82
SymInit: Symbol-SearchPath: '.;C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest;C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\electron\dist;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Igor'
OS-Version: 10.0.22000 () 0x300-0x1
C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\segfault-handler\src\StackWalker.cpp (922): StackWalker::ShowCallstack
C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\segfault-handler\src\StackWalker.cpp (922): StackWalker::ShowCallstack
C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
7711E6F2 (ntdll): (filename not available): RtlIpv4AddressToStringA
771193B1 (ntdll): (filename not available): RtlUnwind
77127176 (ntdll): (filename not available): KiUserExceptionDispatcher
1709E4EC (mscorwks): (filename not available): GetPrivateContextsPerfCounters
170FCD70 (mscorwks): (filename not available): CorExeMain
5DECFB4D (mscorlib.ni): (filename not available): (function-name not available)
19654F81 ((module-name not available)): (filename not available): (function-name not available)
19654D18 ((module-name not available)): (filename not available): (function-name not available)
19650D3A ((module-name not available)): (filename not available): (function-name not available)
19650976 ((module-name not available)): (filename not available): (function-name not available)
19650917 ((module-name not available)): (filename not available): (function-name not available)
C:\Users\Igor\OneDrive\Área de Trabalho\KoffiTest\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
170A7539 (mscorwks): (filename not available): GetPrivateContextsPerfCounters
7711E6F2 (ntdll): (filename not available): RtlIpv4AddressToStringA
771193B1 (ntdll): (filename not available): RtlUnwind
170A7643 (mscorwks): (filename not available): GetPrivateContextsPerfCounters
77127176 (ntdll): (filename not available): KiUserExceptionDispatcher
170A77AC (mscorwks): (filename not available): GetPrivateContextsPerfCounters
1709E4EC (mscorwks): (filename not available): GetPrivateContextsPerfCounters
170FCD70 (mscorwks): (filename not available): CorExeMain
15C2A75D ((module-name not available)): (filename not available): (function-name not available)
5DECFB4D (mscorlib.ni): (filename not available): (function-name not available)
19654F81 ((module-name not available)): (filename not available): (function-name not available)
15F15E6F (EasyInner): (filename not available): RespostaListarUsuariosBio
19654D18 ((module-name not available)): (filename not available): (function-name not available)
19654DBB ((module-name not available)): (filename not available): (function-name not available)
15F1578F (EasyInner): (filename not available): RespostaListarUsuariosBio
1965263A ((module-name not available)): (filename not available): (function-name not available)
19DF4869 (System.ni): (filename not available): (function-name not available)
15EF56D9 (EasyInner): (filename not available): RespostaListarUsuariosBio
19DF793A (System.ni): (filename not available): (function-name not available)
15EF63D7 (EasyInner): (filename not available): RespostaListarUsuariosBio
16FA1B8C (mscorwks): (filename not available): (function-name not available)
15F16983 (EasyInner): (filename not available): RespostaListarUsuariosBio
6C14FD17 (koffi): (filename not available): (function-name not available)
16FB88E1 (mscorwks): (filename not available): (function-name not available)
```

Another strange behavior I noticed is that methods that return strings through parameters end up crashing the program, as is the case with:

`lib.func('uint8_t __stdcall ColetarBilhete(int Inner, _Out_ uint8_t *Tipo, _Out_ uint8_t *Dia, _Out_ uint8_t *Mes, _Out_ uint8_t *Ano, _Out_ uint8_t *Hora, _Out_ uint8_t *Minuto, _Out_ string *Cartao)')`

If I change from `_Out_ string *Cartao` to `_Out_ uint8_t *Cartao` the code works normally but the value returned in `Cartao` is wrong. The method declaration in C# is:

`private static extern byte ColetarBilhete(int Inner, ref byte Tipo, ref byte Dia, ref byte Mes, ref byte Ano, ref byte Hora, ref byte Minuto, StringBuilder Cartao);`

Which data type should I use for this case?

On another computer (the gym's main one) with Windows 7, the app is also installed normally, but it never even manages to get past the initial connection attempt phase and since at that moment I was already short on time I couldn't run the debug properly to get more clues of what was happening, but I'll be able to do new tests to get this information during the weekend.

Anyway, I'm already pretty excited about the initial results! Thanks for all the support so far!

**Comment by nwrkbiz** [comment]
@IgorSamer Strings as output parameter work quite well like so:

https://github.com/Koromix/rygel/issues/8#issuecomment-1333457889

**Comment by IgorSamer** [comment]
@nwrkbiz thanks for the tip! I didn't know that for strings I should use different data types like `char` or `char16`.

Now that I've found [https://koffi.dev/types#fixed-size-string-buffers](https://koffi.dev/types#fixed-size-string-buffers) it's clearer what I should do.

Thank you and when testing I'll come back with the results!

**Comment by IgorSamer** [comment]
I tried several ways but I still couldn't return the expected string. I tried:

`_Out_ char *Cartao` / `_Out_ char16 *Cartao` / `_Out_ char16_t *Cartao` (in these ways the app doesn't crash like with `string` data type)

So I did the following:

```
let tipo = [null]
let dia = [null]
let mes = [null]
let ano = [null]
let hora = [null]
let minuto = [null]
let cartao = ['']

EasyInner.ColetarBilhete(1, tipo, dia, mes, ano, hora, minuto, cartao)
```

But when checking `cartao` the value is: `[ 'ÒÇ░' ]`

So I tried using TextDecoder just like you did [here](https://github.com/Koromix/rygel/issues/8#issuecomment-1333457889) but it always converts the value to an empty string. What I tried was:

```
console.log(new TextDecoder('UTF-8').decode(new Int8Array(cartao[0]))) // empty string
console.log(new TextDecoder('UTF-8').decode(new Int16Array(cartao[0]))) // empty string
console.log(new TextDecoder('UTF-8').decode(new Int32Array(cartao[0]))) // empty string
```

Did I miss something?

**Comment by IgorSamer** [comment]
Hi @Koromix!

First of all, I would like to apologize for getting out of focus on the issue in the previous comments, I just took the opportunity to try to clear up some doubts while doing all the tests possible regarding the main issue in the meantime.

Anyway, I did countless tests on 5 different computers (3 physical and 2 virtual machines) and with the same program made in Electron, where the code implementation is the same and the only difference was the package used to communicate with the DLL. In one program I used `node-ffi-napi` (generating the .exe through `electron-packager`, since with `electron-builder` compilation errors occur) and in another program I used `Koffi` (generating the installer through `electron-builder`).

As I mentioned earlier the results have been very satisfactory since your last update where you fixed the crashes that occurred in random ways. However, there are still two problems that I was able to detect when using Koffi for my case:

1. **Windows 10 or higher**: everything works correctly, however, when calling the `FecharPortaComunicacao` method (to close the communication with the turnstile) after having the connection established with the turnstile, the program crashes. When using the version with `node-ffi-napi` everything works normally;
2. **Windows 7 Professional**: the program cannot start its connection with the turnstile and does not show any errors. It just keeps trying to connect as if the turnstile was configured with an IP other than that of the computer in question, which was not the case. When using the version with `node-ffi-napi` everything works normally.

Just like the other times I used the `segfault-handler` package to detect and generate error logs, and in cases where errors did happen I made sure to generate two logs for the same situation, as I figured that would make your investigations easier.

Here are the results of all the tests done:

| **OS**                                | **Turnstile Connected** | **Package** | **Result**                                                                 | **Notes**    |
|---------------------------------------|-------------------------|-------------|----------------------------------------------------------------------------|--------------|
| Windows 11 Home - 64 bits             | NO                      | NAPI        | OK                                                                         |              |
| Windows 11 Home - 64 bits             | NO                      | Koffi       | OK                                                                         |              |
| Windows 11 Home - 64 bits             | YES                     | NAPI        | OK                                                                         |              |
| Windows 11 Home - 64 bits             | YES                     | Koffi       | Crash on call FecharPortaComunicacao() after the connection is established | [crash1.log](https://gist.github.com/IgorSamer/d41fd0a99241e28e5623638b309ece72) - [crash2.log](https://gist.github.com/IgorSamer/b46023933754c31768456c071afe957d)    |
| Windows 10 Home - 64 bits             | NO                      | NAPI        | OK                                                                         |              |
| Windows 10 Home - 64 bits             | NO                      | Koffi       | OK                                                                         |              |
| Windows 10 Home - 64 bits             | YES                     | NAPI        | OK                                                                         |              |
| Windows 10 Home - 64 bits             | YES                     | Koffi       | Crash on call FecharPortaComunicacao() after the connection is established | [crash1.log](https://gist.github.com/IgorSamer/d08797900275c811082d31f63d1fec32) - [crash2.log](https://gist.github.com/IgorSamer/b402f220cd8a12500e2a5cb88e2bd127)    |
| Windows 10 Home (VM) - 64 bits        | NO                      | NAPI        | OK                                                                         |              |
| Windows 10 Home (VM) - 64 bits        | NO                      | Koffi       | OK                                                                         |              |
| Windows 10 Home (VM) - 64 bits        | YES                     | NAPI        | OK                                                                         |              |
| Windows 10 Home (VM) - 64 bits        | YES                     | Koffi       | Crash on call FecharPortaComunicacao() after the connection is established | [crash1.log](https://gist.github.com/IgorSamer/d7d7b1299917a7afb0c0337de00d99fa) - [crash2.log](https://gist.github.com/IgorSamer/4b396df0f69c6ba25b44c29a3a4ad5a6)    |
| Windows 7 Ultimate SP1 (VM) - 64 bits | NO                      | NAPI        | OK                                                                         |              |
| Windows 7 Ultimate SP1 (VM) - 64 bits | NO                      | Koffi       | OK                                                                         |              |
| Windows 7 Ultimate SP1 (VM) - 64 bits | YES                     | NAPI        | OK                                                                         |              |
| Windows 7 Ultimate SP1 (VM) - 64 bits | YES                     | Koffi       | OK (the connection is closed normally but an error log is generated)       | [error1.log](https://gist.github.com/IgorSamer/727d3223e8eb193591be3bc77eedc2c3) - [error2.log](https://gist.github.com/IgorSamer/fc4caa3a5cf582fa7dde194f8dce8d8c)    |
| Windows 7 Professional SP1 - 64 bits  | NO                      | NAPI        | OK                                                                         |              |
| Windows 7 Professional SP1 - 64 bits  | NO                      | Koffi       | OK                                                                         |              |
| Windows 7 Professional SP1 - 64 bits  | YES                     | NAPI        | OK                                                                         |              |
| Windows 7 Professional SP1 - 64 bits  | YES                     | Koffi       | Never even manages to get past the initial connection attempt phase        |              |

I'm open for tips on how I can debug more effectively to help you with investigations, especially in the case of Windows 7 where no error is shown but the connection is not established.

If you want to do remote access via AnyDesk or if you need any additional information, let me know!

**Comment by Koromix** [comment]
Thanks for the detailed info :)
Sorry, busy week, I'll get back to you next week ;)

**Comment by IgorSamer** [comment]
Hi there!

Do you have any news? I imagine you're quite busy out there, but here in Brazil the next few days will be a holiday and all establishments will be closed so it would be perfect for me to do the tests with my customers' turnstiles :)

**Comment by Koromix** [comment]
Hi!
I'll post some news about this friday!

**Comment by IgorSamer** [comment]
Any news mate? 🤞

**Comment by Koromix** [comment]
I've pushed some changes to the repository to try to fix this, but it's untested.
I have a Windows 7 64-bit machine at home, however I'm not there right now. I will test this on it tomorrow night, and get back to you!

**Comment by Koromix** [comment]
I haven't tested the changes but they are in Koffi 2.3.8 which in now on npm :)
I'll make tests tomorrow but in the meantime maybe it already works.

**Comment by IgorSamer** [comment]
Great! I'll be able to test it again with Windows 7 and the turnstile between tomorrow and Monday and I'll let you know about the result :)

**Comment by IgorSamer** [comment]
Unfortunately the same behavior continues to happen.

In tests with Windows 10, the program keeps crashing after calling the disconnect method (`FecharPortaComunicacao`) after a connection has already been established ([crash1.log](https://gist.github.com/IgorSamer/b2fa712eed14e76d02210f15d2125085), [crash2.log](https://gist.github.com/IgorSamer/c40a01c20f3c98b427c810595e49b86e)).

And in Windows 7 I still can't even make the initial connection with the turnstile.

Just to explain better:

After calling the methods `FecharPortaComunicacao`, `DefinirTipoConexao` and `AbrirPortaComunicacao` (for the initial settings) the app enters a state loop where to check if the connection has been established it checks the value of the `ReceberRelogio` method. If the value is 0, the connection was established and then I can move on to the next states, otherwise the value 1 is returned.

In all cases the `ReceberRelogio` returns 1 on the first few calls and then about 2~5 seconds later it returns 0 and the connection is made. However, in this case on Windows 7 the value returned is always 1 regardless of how long I wait.

Remembering that the same code using `Koffi` works normally with other Windows (with the exception of the crash when disconnecting) and using the same code but with `node-ffi-napi` everything happens the same way, with the difference that it manages to connect normally also on that same computer with Windows 7.

Is there any way to debug what happens at connection time on Windows 7 when using node-ffi-napi and also when using Koffi so we can check the differences and gather more information for you to be able to fix this? If yes, how? 🙏🏻

Thanks!

**Comment by IgorSamer** [comment]
Just bringing some good news :)

I finally learned to work with strings as output parameter thanks to your help @nwrkbiz 🎉

> @IgorSamer Strings as output parameter work quite well like so:
> 
> [#8 (comment)](https://github.com/Koromix/rygel/issues/8#issuecomment-1333457889)
> 
> You need to know the length through.

At the first time I tried I was totally confused even looking into your code, but today I took a look again and did several tests until I understood what really needed to be done. Just for anyone who might have the same question, what I did to get it working was:

In the method definition:

`_Out_ uint8_t *Cartao // used uint8_t instead of char or string`

Then:

```
let Cartao = new Uint8Array(14); // 14 is the length of Cartao = 00000000000000

EasyInner.ColetarBilhete(1, Tipo, Dia, Mes, Ano, Hora, Minuto, Cartao);

Cartao = new TextDecoder('UTF-8').decode(Cartao);
```

Now the only problem that remains is the connection never established on Windows 7 and the crashes when I call the disconnection method on Windows 10 and above :/

**Comment by IgorSamer** [comment]
I have awesome news!

Since when I did the tests on countless computers with different versions of Windows I found it strange that the connection was not established only in that specific Windows 7, while with others it worked normally.

Today during my tests I was able to generate an installer for the version of the app that uses node-ffi-napi through electron-builder. When installing the program on the Windows 7 computer I noticed that the same behavior that happened using Koffi (not establishing the connection) this time was also happening with node-ffi-napi.

It was then that I began to notice what I had done differently from other times and then I noticed that it could be something related to the place where the program had been installed. I remembered that whenever I used electron-packager I simply moved the generated build to the Desktop and then decided to reinstall the program on the Desktop instead of C:\Program Files (x86).

Result: the connection started to be established normally!

I did the same with the version that uses Koffi: I installed it on the Desktop and for the first time it connected to the turnstile from that computer! 🚀

I apologize for all this confusion but at no time did it cross my mind that it could be something related to where the program was installed, since the installer always requires administrator permissions and everything has always worked fine in other versions of Windows and even in the same version of Windows 7 on another computer.

So far I just don't know what's different about the structure of this specific computer that doesn't allow the connection not to be established if the program is installed in the Program Files folder, but luckily we now know that it's not something with the structure of Koffi itself :)

**Comment by IgorSamer** [comment]
I also found out how to generate logs to detect possible failures in the DLL and then found out which error is always being triggered when calling the `FecharPortaComunicacao` method after having the connection established:

```
Log 18/03/2023 13:32:18 - Error: The given key was not present in the dictionary.
Log 18/03/2023 13:32:18 - Error path:
```

Most of the time the error path is empty, but one time it logged the following:

```
Log 19/03/2023 14:28:19 - Error: The given key was not present in the dictionary.
Log 19/03/2023 14:28:19 - Error path: at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Topdata.Inner.Interface.InnerInterface.RemoverConexoes(Int32 numeroInner)
   at Topdata.Inner.Interface.InnerInterface.RaiseDisconnected(Int32 numerInner)
```

I noticed that this log is always generated also when I use node-ffi-napi with the difference that it manages to handle it and everything continues to work normally, while with Koffi the program stops working and crashes.

I hope this information can help you :))

**Comment by IgorSamer** [comment]
Hi!

Any chance of solving this crash with the information I passed?

I understand that it is the company that supplies the DLL that should fix this and I even contacted them reporting the failure that does not crash the program but is also generated when using the example executables provided in their SDK. However, unfortunately the developer support is horrible and I haven't heard back from them about this issue for weeks.

I myself do not recommend this company to any of my new clients and even if they come to correct this behavior (which I find difficult) it would be interesting if Koffi could handle this type of failure as well.

I'm sorry again for the previous confusions and hope this improvement can be made 🤞
